spring.application.name=demo
# for https
server.forward-headers-strategy=framework 

spring.datasource.url = jdbc:mysql://localhost:3306/assetarc?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username = root
spring.datasource.password = King
spring.jpa.hibernate.ddl-auto = update